server:
  port: 8080
spring:
  datasource:
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
      mode: never
  jpa:
    database: postgresql
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  jackson:
    visibility:
      field: none
      setter: none
      getter: any
      is-getter: any
    deserialization:
      fail-on-unknown-properties:
jwt:
  secret:
    key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  permit:
    all:
      - /v1/auth/login
      - /v1/users/registration
      - v1/specializations
      - v1/doctors/adding
      - v1/doctors/bySpecialization/**
      - v1/doctors/{doctorId}/availability
      - v1/appointments
      - v1/appointments/**
      - v1/appointments/user