spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/med-hub-db
    username: postgres
    password: password

jwt:
  permit:
    all:
      - /swagger-ui/**
      - /swagger-resources/*
      - /v3/api-docs/**
      - /v1/auth/login
      - /v1/users/registration
      - v1/specializations
      - v1/doctors/adding
      - v1/doctors/getAllDoctors
      - v1/doctors/bySpecialization/**
      - v1/doctors/{doctorId}/availability
      - v1/appointments
      - v1/appointments/**
      - v1/appointments/user
